name: conda_freeze
channels:
  - conda-forge
dependencies:
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.5.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - contourpy=1.0.7
  - control=0.9.3.post2
  - cryptography=40.0.2
  - cycler=0.11.0
  - fonttools=4.39.4
  - freetype=2.12.1
  - h5py=3.8.0
  - hdf5=1.14.0
  - idna=3.4
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.0.1
  - libcxx=16.0.3
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsqlite=3.41.2
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libzlib=1.2.13
  - llvm-openmp=16.0.3
  - matplotlib-base=3.7.1
  - munkres=1.1.4
  - ncurses=6.3
  - numpy=1.24.3
  - openjpeg=2.5.0
  - openssl=3.1.0
  - packaging=23.1
  - pandas=2.0.1
  - pathlib=1.0.1
  - pillow=9.5.0
  - pip=23.1.2
  - platformdirs=3.5.1
  - pooch=1.7.0
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3
  - readline=8.2
  - requests=2.29.0
  - scipy=1.10.1
  - setuptools=67.7.2
  - six=1.16.0
  - slycot=0.5.4
  - tk=8.6.12
  - tomli=2.0.1
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wheel=0.40.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zstd=1.5.2
